"""empty message

Revision ID: 91df4847ba97
Revises: 
Create Date: 2017-03-01 22:13:14.865962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91df4847ba97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profession', sa.String(length=60), nullable=True),
    sa.Column('marital_status', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_first_name'), 'person', ['first_name'], unique=False)
    op.create_index(op.f('ix_person_last_name'), 'person', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_last_name'), table_name='person')
    op.drop_index(op.f('ix_person_first_name'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
